# 请根据自身需求修改
app_title: xApp-prod
app_summary: xxApp-prod
app_description: xxxApp-prod
app_version: 1.0.0
app_debug: false
app_log_dir: ./logs
app_disable_docs: true
app_allow_origins:
  - '*'
# #
redis_host:
redis_port:
redis_db:
redis_password:
redis_max_connections:
db_url: sqlite:///app_prod.sqlite
db_async_url: sqlite+aiosqlite:///app_prod.sqlite
