# 请根据自身需求修改
app_title: xApp-test
app_summary: xxApp-test
app_description: xxxApp-test
app_version: 1.0.0
app_debug: true
app_log_dir: ./logs
app_disable_docs: false
app_allow_origins:
  - '*'
# #
redis_host:
redis_port:
redis_db:
redis_password:
redis_max_connections:
db_url: sqlite:///app_test.sqlite
db_async_url: sqlite+aiosqlite:///app_test.sqlite
